name: iOS Build (React Native Expo)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log System Details
        run: |
          echo "macOS Version: $(sw_vers -productVersion)"
          echo "RAM: $(sysctl -n hw.memsize | awk '{print $1/1024/1024/1024 " GB"}')"
          echo "CPU Cores: $(sysctl -n hw.ncpu)"
          echo "Disk Space: $(df -h / | tail -1 | awk '{print $4}')"
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Dependencies
        run: yarn install

      - name: Prepare iOS Build
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS App
        env:
          XCODE_WORKSPACE: "ios/YourApp.xcworkspace" # Update this with your workspace name
          XCODE_SCHEME: "YourApp"  # Update with your app scheme name
        run: |
          cd ios
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -derivedDataPath build
          cd ..
      
      - name: Archive the Build
        run: |
          mkdir -p artifacts
          cp -r ios/build/Build/Products/Release-iphoneos/*.app artifacts/
          echo "Build archived successfully."

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: artifacts/
