name: Build iOS IPA

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js & Expo CLI
        run: |
          npm install -g expo-cli
          npm install  

      - name: Generate iOS Native Files (Only If Missing)
        run: |
          if [ ! -d "ios" ]; then
            expo prebuild --platform ios
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App for Archive
        run: |
          xcodebuild archive \
            -workspace ios/exposchoolapp.xcworkspace \
            -scheme exposchoolapp \
            -archivePath ios/build/exposchoolapp.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Generate exportOptions.plist
        run: |
          cat <<EOF > ios/exportOptions.plist
          {
            "method": "development",
            "compileBitcode": false,
            "destination": "export",
            "signingStyle": "manual",
            "signingCertificate": "",
            "signingTeam": "",
            "provisioningProfiles": {}
          }
          EOF

      - name: Export IPA File
        run: |
          mkdir -p ios/build/output
          xcodebuild -exportArchive \
            -archivePath ios/build/exposchoolapp.xcarchive \
            -exportPath ios/build/output \
            -exportOptionsPlist ios/exportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Debug List Exported Files
        run: |
          echo "Listing exported files:"
          ls -R ios/build/output/

      - name: Upload iOS IPA Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-build
          path: ios/build/output/
          if-no-files-found: error
