name: Build iOS Simulator App

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js & Expo CLI
        run: |
          npm install -g expo-cli
          npm install  
      - name: Generate iOS Native Files (Only If Missing)
        run: |
          if [ ! -d "ios" ]; then
            expo prebuild --platform ios
          fi
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app for Simulator
        run: |
          xcodebuild build \
            -workspace ios/exposchoolapp.xcworkspace \
            -scheme exposchoolapp \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath ios/build
      - name: Debug:List Generated Files
        run: |
          echo "Listing generated files:"
          ls -R ios/build/Build/Products/
      - name: Upload Entire iOS Build Folder
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: ios/build/
          if-no-files-found: warn
