name: iOS Development Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Install Xcode CLI Tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Initialize EAS Project
        run: |
          eas init --id=$(uuidgen) || true

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --silent
          cd ..

      - name: Build iOS Development App Locally
        run: |
          eas build --platform ios --profile development --local --non-interactive
          
      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: ./build/**/*.app
